# Generated by Django 4.2.2 on 2023-07-01 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=500)),
                ('actual_title', models.TextField()),
                ('actual_response_by_http', models.CharField(max_length=20)),
                ('actual_response_by_https', models.CharField(max_length=20)),
                ('actual_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('expected_title', models.TextField()),
                ('expected_response_by_http', models.CharField(max_length=20)),
                ('expected_response_by_https', models.CharField(max_length=20)),
                ('expected_text', models.TextField()),
                ('last_check_details', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
