# Generated by Django 4.2.2 on 2023-07-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='actual_text',
            new_name='has_expected_text',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='actual_title',
            new_name='has_expected_title',
        ),
    ]
