# Generated by Django 4.2.2 on 2023-07-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0002_rename_actual_text_check_has_expected_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='has_expected_text',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='has_expected_title',
            field=models.BooleanField(),
        ),
    ]
