# Generated by Django 4.2.2 on 2023-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0004_alter_check_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='last_check_details',
        ),
        migrations.AddField(
            model_name='url',
            name='failed_check_details',
            field=models.TextField(default='ok'),
        ),
    ]
