# Generated by Django 4.2.2 on 2023-07-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0005_remove_url_last_check_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='failed_check_details',
            new_name='check_details',
        ),
    ]
