# Generated by Django 4.2.2 on 2023-07-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0006_rename_failed_check_details_url_check_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='actual_response_by_http',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='actual_response_by_https',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='expected_response_by_http',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='expected_response_by_https',
            field=models.IntegerField(),
        ),
    ]
