# Generated by Django 4.2.2 on 2023-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='has_expected_description',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='expected_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
